BookStore/Controllers/AuthorController.cs
using BusinessLogicLayer.Services.Interface;
using DataEntities.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthor _author;

        public AuthorController(IAuthor author)
        {
            _author = author;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShowAuthorDetails(int id)
        {
            ViewBag.booksOfAuthor = _author.GetAuthorDetails(id);
            ViewBag.aboutAuthor = _author.GetAuthorBooks(id);
            return View();
        }

        // GET
        public IActionResult UpdateAuthor(int id)
        {
            var author = _author.GetAuthorDetails(id);
            _author.UpdateAuthor(author);
            return View(author);
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateAuthor(Author author)
        {
            if (ModelState.IsValid)
            {
                _author.UpdateAuthor(author);
                return RedirectToAction("Index", "Home");
            }
            return View(author);
        }

        public IActionResult DeleteAuthor(int id)
        {
            _author.DeleteAuthor(id);
            _author.DeleteAuthorBooks(id);
            return RedirectToAction("Index", "Home");
        }

        // GET
        public IActionResult AddAuthor()
        {
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddAuthor(Author author)
        {
            if (ModelState.IsValid)
            {
                _author.AddAuthor(author);
                return RedirectToAction("Index", "Home");
            }
            return View();
        }
    }
}

BookStore/Controllers/BookController.cs
using BusinessLogicLayer.Services.Interface;
using DataEntities.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class BookController : Controller
    {
        private readonly IBook _book;
        private readonly IAuthor _author;
        public BookController(IBook book, IAuthor author)
        {
            _book = book;
            _author = author;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ShowBookDetails(int id)
        {
            var book = _book.GetBookDetails(id);
            var author = _author.GetAuthorDetails(book.AuthorId);
            ViewBag.author = author;
            ViewBag.book = book;
            return View();
        }

        // GET
        public IActionResult UpdateBook(int id)
        {
            var book = _book.GetBookDetails(id);
            var authors = _author.GetAuthorList();
            ViewBag.authors = authors;
            ViewBag.book = book;
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdateBook(Book book)
        {
            if (ModelState.IsValid)
            {
                _book.UpdateBook(book);
                return RedirectToAction("Index", "Home");
            }
            return View(book);
        }

        public IActionResult DeleteBook(int id) // NotFound is used here only
        {
            if(_book.DeleteBook(id) == false)
            {
                return NotFound();
            }
            return RedirectToAction("Index", "Home");
        }

        // GET
        public IActionResult AddBook()
        {
            ViewBag.authors = _author.GetAuthorList();
            return View();
        }

        // POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddBook(Book book)
        {
            if (ModelState.IsValid)
            {
                _book.AddBook(book);
                return RedirectToAction("Index", "Home");
            }
            return View(book);
        }
    }
}

BookStore/Controllers/HomeController.cs
using BusinessLogicLayer.Services.Interface;
using DataEntities.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBook _book;
        public HomeController(IBook book)
        {
            _book = book;
        }

        public IActionResult Index()
        {
            IEnumerable<Book> objBook = _book.GetBookList();
            return View(objBook);
        }
    }
}

BookStore/Views/Author/AddAuthor.cshtml
@using DataEntities.Models;
@model Author

@{
    ViewData["Title"] = "Add Author";
}

<form method="post">
    <div class="border" p-3 mt-4>
        <div class="row pb-2">
            <h2 class="text-primary">Add an author</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Name"></label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Address"></label>
            <input asp-for="Address" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="ImagePath"></label>
            <input asp-for="ImagePath" class="form-control" />
        </div>
        <button type="submit" class="btn btn-primary" style="width: 150px">Create</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
    </div>
</form>

BookStore/Views/Author/ShowAuthorDetails.cshtml
@using DataEntities.Models;
@{
    ViewData["Title"] = "Author Details";
    var author = ViewBag.aboutAuthor;
    var authorBooks = ViewBag.booksOfAuthor;
}

<div class="w3-container">
    <img src="@author.ImagePath" alt="Image" style="width: 200px; height: 200px;" />
    <h3>Name: @author.Name</h3>
    <h3>Address: @author.Address</h3>
    <br />
    <table class="table table-bordered table-striped" style="width: 50%; text-align:center">
        <thead>
            <tr>
                <th>Books</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var book in authorBooks)
            {
                <tr>
                    <td width="50%">
                        <a asp-controller="Book" asp-action="ShowBookDetails" asp-route-id="@book.Id">@book.Title</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a asp-controller="Author" asp-action="UpdateAuthor" asp-route-id=@author.Id class="btn btn-primary mx-2">Update</a>
    @*<a asp-controller="Home" asp-action="DeleteAuthor" asp-route-id=@author.Id class="btn btn-danger mx-2">Delete</a>*@

    @*delete button with a confirmation pop up*@
    <a onclick="return confirm('All books of this author will be deleted. Are you sure to delete?')" asp-controller="Author" asp-action="DeleteAuthor" asp-route-id=@author.Id class="btn btn-danger mx-2">Delete</a>
    <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Book List</a>

</div>

BookStore/Views/Author/UpdateAuthor.cshtml
@using DataEntities.Models;
@model Author

@{
    ViewData["Title"] = "Update Author";
}

<form method="post" asp-action="UpdateAuthor">
    <div class="border" p-3 mt-4>
        <div class="row pb-2">
            <h2 class="text-primary">Update Author info</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label>Name</label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="mb-3">
            <label>Address</label>
            <input asp-for="Address" class="form-control" />
        </div>
        <div class="mb-3">
            <label>Image Link</label>
            <input asp-for="ImagePath" class="form-control" />
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Book List</a>
    </div>
</form>

BookStore/Views/Book/AddBook.cshtml
@using DataEntities.Models;
@model Book

@{
    ViewData["Title"] = "Add Book";
    var authors = ViewBag.authors;
}

<form method="post">
    <div class="border" p-3 mt-4>
        <div class="row pb-2">
            <h2 class="text-primary">Add a book</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label asp-for="Title"></label>
            <input asp-for="Title" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="CoverPath"></label>
            <input asp-for="CoverPath" class="form-control" />
        </div>
        <div class="mb-3">
            <label asp-for="Language"></label>
            <input asp-for="Language" class="form-control" />
        </div>
        <div class="mb-3">
            <label>Select an author</label>
            <select name="authorId">
                @foreach (var author in authors)
                {
                    <option value="@author.Id">@author.Name</option>
                }
            </select>
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Create book</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Book List</a>
        <a asp-controller="Author" asp-action="AddAuthor" class="btn btn-success mx-2" style="vertical-align:middle; align-items: center">Add a new author</a>


    </div>
</form>

BookStore/Views/Book/ShowBookDetails.cshtml
@using DataEntities.Models;
@{
    ViewData["Title"] = "Book Details";
}
<div class="container-md">
    <h3>Book: @ViewBag.book.Title</h3>
    <h3>Author: <a asp-controller="Author" asp-action="ShowAuthorDetails" asp-route-authorid="@ViewBag.book.AuthorId">@ViewBag.author.Name</a></h3>
    <h3>Language: @ViewBag.book.Language</h3>
    <br />

    <img src="@ViewBag.book.CoverPath" alt="Image" style="width: 200px; height: 300px;" />

    <br />
    <br />
    <a asp-controller="Book" asp-action="UpdateBook" asp-route-id="@ViewBag.book.Id" class="btn btn-primary mx-2">Update</a>
    <a asp-controller="Book" asp-action="DeleteBook" asp-route-id="@ViewBag.book.Id" class="btn btn-danger mx-2">Delete</a>
    <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Book List</a>

</div>

BookStore/Views/Book/UpdateBook.cshtml
@using DataEntities.Models;
@{
    ViewData["Title"] = "Update Book";
    var title = ViewBag.book.Title;
    var coverPath = ViewBag.book.CoverPath;
    var language = ViewBag.book.Language;
    var authors = ViewBag.authors;
}

<form method="post" asp-action="UpdateBook">
    <div class="border" p-3 mt-4>
        <div class="row pb-2">
            <h2 class="text-primary">Update Book info</h2>
            <hr />
        </div>

        <div class="mb-3">
            <label>Title</label>
            <input asp-for=@title class="form-control" />
        </div>
        @*        <div class="mb-3">
        <label>Author</label>
        <input asp-for=@author class="form-control" />
        </div>*@
        <div class="mb-3">
            <label>Book Cover Link</label>
            <input asp-for=@coverPath class="form-control" />
        </div>
        <div class="mb-3">
            <label>Language</label>
            <input asp-for=@language class="form-control" />
        </div>

        @*dropdown menu*@
        <div class="mb-3">
            <label>Select an author</label>
            <select name="authorId">
                @foreach (var author in authors)
                {
                    <option value="@author.Id">@author.Name</option>
                }
            </select>
        </div>

        <button type="submit" class="btn btn-primary" style="width: 150px">Update</button>
        <a asp-controller="Home" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to Book List</a>
        <a asp-controller="Author" asp-action="AddAuthor" class="btn btn-success mx-2" style="vertical-align:middle; align-items: center">Add a new author</a>
    </div>
</form>

BookStore/Views/Home/Index.cshtml
@using DataEntities.Models;
@model IEnumerable<Book>
@{
    ViewData["Title"] = "Home Page";
}

<div class="container-md">
    <table class="table table-bordered table-striped" style="width: 80%; text-align:center">
        <thead>
            <tr>
                <th width="50%">
                    Books
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var obj in Model)
            {
                <tr>
                    <td width="50%">
                        @obj.Title
                    </td>
                    <td>
                        <div class="w-75 btn-group" role="group">
                            <a asp-controller="Book" asp-action="ShowBookDetails" asp-route-id="@obj.Id" class="btn btn-primary mx-2">Details</a>
                        </div>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    <a asp-controller="Book" asp-action="AddBook" class="btn btn-success mx-2" style="vertical-align:middle; align-items: center">Add a new book</a>
</div>

BookStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookStore</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BookStore.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookStore</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BookStore - <a asp-area="" asp-controller="Home">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>